club_membre:
    resource: "@ClubBundle/Resources/config/routing/membre.yml"
    prefix:   /membre

club_homepage:
    path:     /
    defaults: { _controller: ClubBundle:Default:index }

delete:
    path:     /delete{id}
    defaults: { _controller: ClubBundle:club:delete }

show:
    path:     /
    defaults:  {_controller: ClubBundle:membre:show }

Membre:
    path:     /Membre/{id}
    defaults:  {_controller: ClubBundle:membre:Membre }

membre_mailling:
    path:     /mailling
    defaults:  {_controller: ClubBundle:membre:mail }


