<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxdfpiw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxdfpiw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRxdfpiw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRxdfpiw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRxdfpiw\appDevDebugProjectContainer([
    'container.build_hash' => 'Rxdfpiw',
    'container.build_id' => 'ca716561',
    'container.build_time' => 1581542098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxdfpiw');
