<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfjltib\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfjltib/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLfjltib.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLfjltib\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLfjltib\appDevDebugProjectContainer([
    'container.build_hash' => 'Lfjltib',
    'container.build_id' => '7da3d899',
    'container.build_time' => 1582734205,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfjltib');
